spring.application.name=Online retail PROJECT

spring.jpa.defer-datasource-initialization=true

spring.messages.basename=i18n/messages
spring.messages.encoding=UTF-8
spring.messages.cache-duration=3600
spring.messages.fallback-to-system-locale=false
