INSERT INTO PRODUCT (NAME, MANUFACTURER, SIZE, PRICE, CURRENT_STOCK, LOW_STOCK_THRESHOLD) VALUES
('Liquid yogurt XXL', 'Pilos', '1.5kg', 1.69, 500, 180),
('Crunchy peanut butter XXL', 'McKennedy', '1kg', 5.79, 80, 15),
('Homemade burek with cheese', 'Store bakery', '220g', 0.85, 30, 5),
('Mayo', 'STAR', '165g', 1.89, 90, 30),
('Long-life milk XXL', 'Ducat', '8x1L', 6.99, 300, 100);

INSERT INTO USERS(USERNAME, PASSWORD, ENABLED)
VALUES('user', '{noop}password', 1);

INSERT INTO USERS(USERNAME, PASSWORD, ENABLED)
VALUES('admin', '{noop}password', 1);

INSERT INTO USERS(USERNAME, PASSWORD, ENABLED)
VALUES('superadmin', '{noop}password', 1);

INSERT INTO AUTHORITIES(USERNAME, AUTHORITY)
VALUES('user', 'ROLE_USER');

INSERT INTO AUTHORITIES(USERNAME, AUTHORITY)
VALUES('admin', 'ROLE_USER');

INSERT INTO AUTHORITIES(USERNAME, AUTHORITY)
VALUES('admin', 'ROLE_ADMIN');

INSERT INTO AUTHORITIES(USERNAME, AUTHORITY)
VALUES('superadmin', 'ROLE_USER');

INSERT INTO AUTHORITIES(USERNAME, AUTHORITY)
VALUES('superadmin', 'ROLE_ADMIN');