CREATE TABLE PRODUCT(
    ID BIGINT GENERATED ALWAYS AS IDENTITY,
    NAME VARCHAR(30) NOT NULL ,
    MANUFACTURER VARCHAR(30) NOT NULL ,
    SIZE VARCHAR(10) NOT NULL ,
    PRICE DECIMAL(10,2) NOT NULL,
    PRIMARY KEY (ID)
);